# ./.tmuxinator.yml

name: topocon
root: ~/ros2_ws/src/ros2_dist_gnn/ros2_dist_gnn

# Optional tmux socket
# socket_name: foo

# Note that the pre and post options have been deprecated and will be replaced by
# project hooks.

# Project hooks

# Runs on project start, always
# on_project_start: command

# Run on project start, the first time
# on_project_first_start: command

# Run on project start, after the first time
# on_project_restart: command

# Run on project exit ( detaching from tmux session )
# on_project_exit: command

# Run on project stop
# on_project_stop: command

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: editor

# Specifies (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

<% log_level = ARGV.include?('--debug') ? 'DEBUG' : 'INFO' %>
log_level: <%= log_level %>

windows:
  - nodes:
      layout: even-horizontal
      synchronize: after
      panes:
        - |
          <%- if args[0] == "mixed" or args[0] == "remote" %>
          ssh -o StrictHostKeyChecking=no -o ForwardAgent=yes -t pi@rpi0.local '/home/pi/ros2_dist_gnn/docker/start_docker.sh ros2_gnn_cont'
          <%- end %>
          ros2 run topocon node --ros-args -r __ns:=/node_0 -p num_nodes:=5 --log-level <%= log_level %> --log-level rcl:=INFO
        - |
          <%- if args[0] == "remote" %>
          ssh -o StrictHostKeyChecking=no -o ForwardAgent=yes -t pi@rpi1.local '/home/pi/ros2_dist_gnn/docker/start_docker.sh ros2_gnn_cont'
          <%- end %>
          ros2 run topocon node --ros-args -r __ns:=/node_1 -p num_nodes:=5 --log-level <%= log_level %> --log-level rcl:=INFO
        - |
          <%- if args[0] == "remote" %>
          ssh -o StrictHostKeyChecking=no -o ForwardAgent=yes -t pi@rpi2.local '/home/pi/ros2_dist_gnn/docker/start_docker.sh ros2_gnn_cont'
          <%- end %>
          ros2 run topocon node --ros-args -r __ns:=/node_2 -p num_nodes:=5 --log-level <%= log_level %> --log-level rcl:=INFO
        - |
          <%- if args[0] == "remote" %>
          ssh -o StrictHostKeyChecking=no -o ForwardAgent=yes -t pi@rpi3.local '/home/pi/ros2_dist_gnn/docker/start_docker.sh ros2_gnn_cont'
          <%- end %>
          ros2 run topocon node --ros-args -r __ns:=/node_3 -p num_nodes:=5 --log-level <%= log_level %> --log-level rcl:=INFO
        - |
          <%- if args[0] == "remote" %>
          ssh -o StrictHostKeyChecking=no -o ForwardAgent=yes -t pi@rpi4.local '/home/pi/ros2_dist_gnn/docker/start_docker.sh ros2_gnn_cont'
          <%- end %>
          ros2 run topocon node --ros-args -r __ns:=/node_4 -p num_nodes:=5 --log-level <%= log_level %> --log-level rcl:=INFO
  - central:
      panes:
        - |
          cd scripts
          python3 graph_server.py
        - ros2 launch foxglove_bridge foxglove_bridge_launch.xml
  - bags:
      layout: even-horizontal
      panes:
        - |
          cd /root/ros2_ws/bags
          history -s "ros2 bag record -e '(/.*\/lambda2|/lambda2_ref)' -o topocon"
        - |
          cd /root/ros2_ws/bags/
          history -s "ros2 bag play sim_formation_slow"
        - |
          cd /root/ros2_ws/bags/
          history -s "ros2 bag record -e '(/.*\/discovery|/lambda2_ref)' -o sim_formation_slow"
